config/routes.rb
Rails.application.routes.draw do

  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :airports
  resources :flights
  resources :bookings
  # Defines the root path route ("/")
  root to: 'flights#index'
end

app/models/airport.rb
class Airport < ApplicationRecord

    has_many :departing_flights, class_name: 'Flight', foreign_key: 'departure_airport_id'
    has_many :arriving_flights, class_name: 'Flight', foreign_key: 'arrival_airport_id'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
belongs_to :flight
has_many :passengers

  accepts_nested_attributes_for :passengers

  delegate :departure_airport, to: :flight
  delegate :arrival_airport, to: :flight
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: 'Airport'
  belongs_to :arrival_airport, class_name: 'Airport'
  has_many :bookings
  def self.available_dates
    where("start_date > ?", Date.today).order(start_date: :asc).pluck(:start_date).uniq
  end
  
end

app/models/passenger.rb
class Passenger < ApplicationRecord
   
    #has_many :bookings
    belongs_to :booking
    

end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController


  def new
    @airport = Airport.new
  end


  def index
    @airports = Airport.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def create
    @booking = Booking.new(allowed_post_params)
    if @booking.save
      redirect_to @booking, notice: 'Your flight was successfully booked.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private 
  
  def allowed_post_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
 
  def index
    @airport_options = Airport.all.map{ |a| ["#{a.code} - #{a.id}", a.id ] }
    @searched_flights = Flight.where(departure_airport_id: params[:departure_airport_id], arrival_airport_id: params[:arrival_airport_id], start_date: params[:start_date])
   
  end





 


end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/airports/index.html.erb
<div class = "flex flex-col">
  <h1 class="font-bold text-4xl">Airports#index</h1>
  <p>Find me in app/views/airports/index.html.erb</p>


<!-- app/views/airports/index.html.erb -->

  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
    <% @airports.each do |airport| %>
      <div class="bg-blue-500 text-white text-center py-4 rounded-md">
        <%= airport.code %>
      </div>
    <% end %>
  </div>

</div>

app/views/bookings/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Bookings#create</h1>
  <p>Find me in app/views/bookings/create.html.erb</p>
</div>

app/views/bookings/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Bookings#index</h1>
  <p>Find me in app/views/bookings/index.html.erb</p>
</div>

app/views/bookings/new.html.erb
<h1>Welcome to booking.new</h1>
<%= form_with model: @booking, class: "d-flex flex-column" do |booking_form| %>
  <%= booking_form.hidden_field :flight_id, value: params[:flight_id] %>
  <div class="m-2 fw-bold">
  <% i=0 %>
    <%= params[:num_passengers].to_i.times do |p|%>
    <div> Passenger n°<%=i%></div>
    <% i += 1 %>
      <%= booking_form.fields_for :passengers, @booking.passengers.build do |passenger_form| %>
        <%= passenger_form.label :name, hidden: true, class: "form-label" %>
        <%= passenger_form.text_field :name, placeholder: "Name", class: "form-control my-3", required: true %>
        <%= passenger_form.label :email, hidden: true, class: "form-label" %>
        <%= passenger_form.email_field :email, placeholder: "Email", class: "form-control my-3", required: true %>
      <% end %>
    </div>
  <% end %>
  <%= booking_form.submit "Confirm booking", class: "btn btn-success ml-1 flex-basis-1 m-2" %>
<% end %>
<p>hello</p>

app/views/bookings/show.html.erb
<h1>Booking N°<%=@booking.id%> </h1>
<h1>Number of passeners <%=@booking.passengers.count%></h1>
<h1>From  <%=@booking.departure_airport.code%></h1>
<h1>to <%=@booking.arrival_airport.code%></h1>
<%  @booking.passengers.each do |passenger| %>
<%=passenger.name%>
<%=passenger.email%>
<h1>|</h1>

    
<% end %>

app/views/flights/index.html.erb
<div class="flex flex-col">
  <h1 class="font-bold text-4xl">Flights#index</h1>
  <p>Find me in app/views/flights/index.html.erb</p>

  <p>PARAMS</p>

  <div class="w-full max-w-lg mx-auto mt-6 flex">
    <%= form_with model: @flight, method: "get", class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" do |f| %>
      <div class="mb-4">
        <%= f.label :departure_airport_id, "Departure airport", class: "block text-gray-700 font-bold mb-2" %>
        <%= f.select :departure_airport_id, options_for_select(@airport_options), {}, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
      </div>

      <div class="mb-4">
        <%= f.label :arrival_airport_id, "Arrival airport", class: "block text-gray-700 font-bold mb-2" %>
        <%= f.select :arrival_airport_id, options_for_select(@airport_options), {}, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
      </div>

      <div class="mb-4">
        <%= f.label :num_passengers, "Passengers", class: "block text-gray-700 font-bold mb-2" %>
        <%= select_tag :num_passengers, options_for_select([1,2,3,4]), class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
      </div>

      <div class="mb-4">
        <%= f.label :start_date, "Departure date", class: "block text-gray-700 font-bold mb-2" %>
        <%= f.select :start_date, options_for_select(Flight.available_dates.map { |date| [date.strftime('%d-%b-%Y'), date] }), {}, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
      </div>

      <div class="flex items-center justify-between">
        <%= f.submit "Search", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
      </div>
    <% end %>
  </div>

 

<% if @searched_flights.any? %>
  <p class="text-3xl font-bold">Flights</p>
  <%= form_with model: @booking, method: "get", class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4", url: new_booking_path do |f| %>
    <% @searched_flights.each do |flight| %>
    <%= f.hidden_field :num_passengers, value: params[:num_passengers] %>
      <div class="flex items-center mb-4">
        <div class="w-1/4">
          <%= f.radio_button :flight_id, flight.id %>
        </div>
        <div class="w-3/4 min-w-0">
          <p class="whitespace-nowrap">
           <%= flight.id %> | <%= flight.departure_airport.code %> -> <%= flight.arrival_airport.code %> | <%= flight.start_date %>
          </p>
        </div>
        
      </div>
    <% end %>
    <div class="flex items-center justify-between">
      <%= f.submit "Book", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    </div>
  <% end %>
<% else %>
  <p>No flights match your search criteria.</p>
<% end %>



<%# <%= link_to "Book", new_booking_path(flight_id: flight.id, num_passengers: params[:num_passengers]) %> %>
<%="intead of submit use the link tag"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="">
    <% flash.each do |type, message| %>
      <% if flash[:success] %>
        <div class="bg-green-500 text-white px-4 py-2 rounded-md mb-4 ">
        <%= flash[:success] %>
        </div>
      <% end %>
      <% if flash[:error] %>
        <div class="bg-red-500 text-white px-4 py-2 rounded-md mb-4 ">
        <%= flash[:error] %>
        </div>
      <% end %>

    <% end %>
      <%= yield %>
    </main>
  </body>
</html>